/* automatically generated by rust-bindgen 0.65.1 */

pub type __kernel_loff_t = core::ffi::c_longlong;
pub type loff_t = __kernel_loff_t;
extern "C" {
    pub fn tb_register_debugfs_files() -> core::ffi::c_int;
}
extern "C" {
    pub fn tb_cleanup_debugfs_files();
}
extern "C" {
    pub fn tb_rs_open() -> *mut core::ffi::c_void;
}
extern "C" {
    pub fn tb_rs_release(arg1: *mut core::ffi::c_void);
}
extern "C" {
    pub fn tb_rs_read(
        arg1: *mut core::ffi::c_void,
        arg2: *mut core::ffi::c_char,
        arg3: usize,
        arg4: *mut loff_t,
    ) -> isize;
}
